apiVersion: v1
kind: Service
metadata:
  name: riseml-minio
spec:
  {{- if .Values.nodePorts }}
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 31874
      name: data
    - port: 9001
      targetPort: 9001
      nodePort: 31875
      protocol: TCP
      name: output
  {{- else }}
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: data
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: output
  {{- end }}
  selector:
    app: riseml-minio
