apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: riseml-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: riseml-registry
        type: system
    spec:
      {{- if .Values.scheduleOnMaster }}
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
      {{- end}}
{{- include "riseml.nodeSelectors.yaml" . | indent 6 }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: type
                  operator: In
                  values:
                  - system
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: registry
        image: registry:2
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-volume
          subPath: {{ .Values.registry.persistence.subPath }}
      volumes:
      - name: registry-volume
      {{- if .Values.registry.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.registry.persistence.existingClaim | default "riseml-registry-claim" }}
      {{- else }}
        emptyDir: {}
      {{- end }}
